config/routes.rb
Rails.application.routes.draw do

  
  get "admin" => "admin#index"
  
  get "admin/semester" => "admin#semester"
  
  get "admin/student_teams" => "admin#student_teams"
  post "admin/student_teams/generate" => "admin#generate_student_teams"
  
  get "admin/instructors" => "admin#instructors"
  post "admin/instructors/new" => "admin#create_instructor"
  
  get "admin/rubric" => "admin#rubric"

  get 'comments/index'

  get "logout" => "logout#index"

  get "login" => "login#index"
  post "login" => "login#login"
  
  get "comments" => "comments#index"

  resources :projects
  resources :instructors
  resources :student_teams
  resources :customers
  
  root 'welcome#index'
  
  get "/student_teams/:id/submit_story/" => "student_teams#new_story"
  
  get "/student_teams/:id/reset_password/" => "student_teams#reset_password"
  post "/student_teams/:id/reset_password/" => "student_teams#perform_reset_password"
  
  post "/student_teams/:id/submit_story/" => "student_teams#create_story"
  post "/student_teams/:id/assign/" => "student_teams#assign"
  post "/student_teams/:id/add_gsi_comments/:iter_id/" => "student_teams#add_gsi_comments"
  post "/projects/:id/assign/" => "projects#assign"
  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
    has_many :projects
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
    has_many :student_teams, dependent: :destroy
end

app/models/iteration.rb
class Iteration < ActiveRecord::Base
  
  belongs_to :student_team
    
  def iteration_string
    "Iteration #{(self.iteration + 1) / 2}-#{(self.iteration - 1) % 2 + 1}" 
  end

  def created_at_string
    self.created_at.strftime("%m/%d/%Y - %I:%M%p")
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
    belongs_to :student_team
    belongs_to :customer
end

app/models/student_team.rb
class StudentTeam < ActiveRecord::Base
    has_many :iterations, dependent: :destroy
    belongs_to :instructor
    has_one :project
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  
  def index
    super
    return display_unauthorized_message if not logged_in_as_admin
  end
  
  #----------------------------------------------------------------------------
  # * Semester Controls
  #----------------------------------------------------------------------------
  
  def semester
    return display_unauthorized_message if not logged_in_as_admin
  end
  
  #----------------------------------------------------------------------------
  # * Student Team Controls
  #----------------------------------------------------------------------------
  
  def student_teams
    return display_unauthorized_message if not logged_in_as_admin
    dummy_project = Project.new(title: "Unassigned", content: "Unassigned")
    @student_teams = StudentTeam.all
    @projects = @student_teams.map { |team| team.project || dummy_project }
  end
  
  def generate_student_teams
    return display_unauthorized_message if not logged_in_as_admin
    teams_to_generate = params[:student_team][:amount].to_i
    current_team_count = StudentTeam.count
    if teams_to_generate < 0 or teams_to_generate > 100
      return render body: "Error: Cannot generate #{teams_to_generate} teams."
    end
    create_student_teams(teams_to_generate, current_team_count)
    redirect_to(action: "student_teams")
  end
  
  #----------------------------------------------------------------------------
  # * Instructor Controls
  #----------------------------------------------------------------------------
  
  def instructors
    return display_unauthorized_message if not logged_in_as_admin
    @instructors = Instructor.all
  end
  
  def create_instructor
    return display_unauthorized_message if not logged_in_as_admin
    instructor_hash = instructor_params
    instructor_hash[:password] = generate_random_password
    Instructor.create(instructor_hash)
    redirect_to(action: "instructors")
  end
  
  private
  
  #---------------------------------------------------------------------------
  # * Helper Methods
  #---------------------------------------------------------------------------
  
  def generate_random_password
    return (0...8).map { (65 + rand(26)).chr }.join
  end
  
  def create_student_teams(amount, curr_index)
    amount.times { |i|
      sid = i + curr_index + 1
      name = "Group #{sid}"
      username = "group#{sid}"
      password = generate_random_password
      StudentTeam.create(name: name, username: username, password: password)
    }
  end
  
  def instructor_params
    params.require(:instructor).permit(:name, :email)
  end
  
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  
  def login
    # originally email. Want to change it back to email to make the tests pass again?
    username = params[:login_form][:username]
    password = params[:login_form][:password]
    return if login_as_student_team(username, password) 
    return if login_as_instructor(username, password)
    return if login_as_admin(username, password)
    return if login_as_customer(username, password)
    flash[:notice] = "There is no user associated with these login details."
    redirect_to(action: "index")
  end
  
  private
  
  def login_as_student_team(username, password)
    student_team = StudentTeam.find_by(name: username, password: password)
    if student_team
      session[:user_type] = 1
      session[:user_id] = student_team.id
      redirect_to(root_path)
      return true
    end
    return false
  end
  
  def login_as_instructor(username, password)
    instructor = Instructor.find_by(name: username, password: password)
    if instructor
      session[:user_type] = 2
      session[:user_id] = instructor.id
      redirect_to(root_path)
      return true
    end
    return false
  end
  
  def login_as_admin(username, password)
    if username == Rails.configuration.x.admin_username and
        password == Rails.configuration.x.admin_password
      session[:user_type] = 3
      session[:user_id] = 1
      redirect_to(root_path)
      return true
    end
    return false
  end
  
  def login_as_customer(username, password)
    customer = Customer.find_by(name: username, password: password)
    if customer
      session[:user_type] = 4
      session[:user_id] = customer.id
      redirect_to(root_path)
      return true
    end
    return false
  end
  
end

app/controllers/logout_controller.rb
class LogoutController < ApplicationController
  
  def index
    [:user_type, :user_id, :profile_path].each { |sym|
      session.delete(sym)
    }
    redirect_to(root_path)
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    
    private
    
    def reject_existing_user(team_name)
      if Instructor.exists?(name: team_name) or 
            StudentTeam.exists?(name: team_name)
        flash[:notice] = "A Student Team or Instructor with this name already exists!"
        redirect_to(action: 'new')
        return true
      end
      return false
    end
    
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/common2_helper.rb
module Common2Helper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/student_teams_helper.rb
module StudentTeamsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/_admin_controls.haml
#left-admin

  %h3 Admin Controls
    
  %ul
  
    %li= link_to("Manage Semester", "/admin/semester")
    %li= link_to("Manage Student Teams", "/admin/student_teams")
    %li= link_to("Manage Instructors", "/admin/instructors")
    %li= link_to("Manage Rubric", "/admin/rubric")

app/views/admin/index.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "admin/admin_controls"
      
  #profile-right
  
    %h2 Current Semester: Spring, Year of Our Lord 2016

app/views/admin/instructors.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "admin/admin_controls"
      
  #profile-right
  
    %h2 List of Instructors

    %table
      %thead
        %tr
          %th Name
          %th E-mail
          %th Reset
          %th Delete
          %th Temp Password
      %tbody
        - @instructors.each_with_index do |instructor|
          %tr
            %td= instructor.name
            %td= instructor.email
            %td Reset Password
            %td Delete
            %td= instructor.password
    
    %h2 Add New Instructor
  
    = form_tag "/admin/instructors/new" do
      = label :instructor, :name, 'Name:'
      %br
      = text_field :instructor, 'name', id: 'name', required: true
      %p
      = label :instructor, :email, 'E-mail Address:'
      %br
      = text_field :instructor, 'email', id: 'email', required: true
      %p
      = submit_tag 'Add New Instructor', data: { disable_with: "Please wait..." }

app/views/admin/semester.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "admin/admin_controls"
      
  #profile-right
  
    %h2 Current Semester: Spring, Year of Our Lord 2016

app/views/admin/student_teams.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "admin/admin_controls"
      
  #profile-right
  
    %h2 List of Student Teams

    %table
      %thead
        %tr
          %th ID
          %th Username
          %th Name
          %th Project
          %th Reset
          %th Delete
          %th Temp Password
      %tbody
        - @student_teams.each_with_index do |team, i|
          %tr
            %td= team.id
            %td= team.username
            %td= team.name
            %td= @projects[i].title
            %td Reset Password
            %td Delete
            %td= team.password
    %p
    Export to CSV
    
    %h2 Generate Student Teams
    
    = form_tag "/admin/student_teams/generate" do
      = label :student_team, :amount, "Teams to Generate: "
      = number_field :student_team, 'amount', id: 'student-team-amount', required: true
      %p
      = submit_tag 'Create New Teams', data: { disable_with: "Please wait..." }

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectPortal</title>
  <link href='https://fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<div id="header">
  <%= link_to("ProjectPortal", "/") %>
</div>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>

<%= yield %>

</body>
</html>

app/views/main/_profile_login.haml
#login-settings.profile
    ="[#{link_to("Project List", projects_path)}]".html_safe
    - if not session[:profile_path].empty?
        ="[#{link_to("Student List", student_teams_path)}]".html_safe
        - if @current_user and @current_user.is_a?(Instructor)
            ="[#{link_to("Comment List", "/comments")}]".html_safe
        ="[#{link_to('Profile Page', session[:profile_path])}]".html_safe
        ="[#{link_to('Logout', logout_path)}]".html_safe
    - else
        ="[#{link_to('Login', login_path)}]".html_safe

app/views/main/_settings_login.haml
#login
  - if not session[:profile_path].empty?
    ="[#{link_to('Profile Page', session[:profile_path])}]".html_safe
    ="[#{link_to('Logout', logout_path)}]".html_safe
  - else
    ="[#{link_to('Login', login_path)}]".html_safe

app/views/main/_sidebar.haml
#sidebar
    =link_to("Project List", projects_path, :id => 'plist', :class => 'panelbutton')
    =link_to("Student List", student_teams_path, :id => 'slist', :class => 'panelbutton')
    - if @current_user and @current_user.is_a?(Instructor)
        =link_to("Comment List", "/comments", :id => 'clist', :class => 'panelbutton')