config/routes.rb
Rails.application.routes.draw do

  
  get "admin" => "admin#index"
  
  get "admin/semester" => "admin#semester"
  
  get "admin/student_teams" => "admin#student_teams"
  post "admin/student_teams/generate" => "admin#generate_student_teams"
  
  get "admin/instructors" => "admin#instructors"
  post "admin/instructors/new" => "admin#create_instructor"
  
  get "admin/rubric" => "admin#rubric"

  get 'comments/index'

  get "logout" => "logout#index"

  get "login" => "login#index"
  post "login" => "login#login"
  
  get "comments" => "comments#index"

  resources :projects
  resources :instructors
  resources :student_teams
  resources :customers
  
  root 'welcome#index'
  
  get "/student_teams/:id/submit_story/" => "student_teams#new_story"
  
  get "/student_teams/:id/reset_password/" => "student_teams#reset_password"
  post "/student_teams/:id/reset_password/" => "student_teams#perform_reset_password"
  
  post "/student_teams/:id/submit_story/" => "student_teams#create_story"
  post "/student_teams/:id/assign/" => "student_teams#assign"
  post "/student_teams/:id/add_gsi_comments/:iter_id/" => "student_teams#add_gsi_comments"
  post "/projects/:id/assign/" => "projects#assign"
  

end

app/models/student_team.rb
class StudentTeam < ActiveRecord::Base
    has_many :iterations, dependent: :destroy
    belongs_to :instructor
    has_one :project
end

app/controllers/student_teams_controller.rb
class StudentTeamsController < UserController
        
    def index
      super
      dummy_project = Project.new(title: "Unassigned", content: "Unassigned")
      @student_teams = StudentTeam.all
      @projects = @student_teams.map { |team| team.project || dummy_project }
    end

    
    def edit
      return display_unauthorized_message if not can_edit_profile_page?(params[:id].to_i)
      identify_student_team
    end
    
    def update
      return display_unauthorized_message if not can_edit_profile_page?(params[:id].to_i)
      @student_team = StudentTeam.find(params[:id])
      attributes = [:name, :github_link, :heroku_link, :codeclimate_link, :pivotal_link]
      attributes.each { |attr|
         @student_team.update_attribute(attr, params[:student_team][attr])
      }
      redirect_to(student_team_path(@student_team))
    end
    
    def show
      return display_unauthorized_message if not access_profile_page?(params[:id].to_i)
      identify_student_team
    end
    
    def new_story
      edit
    end
    
    def create_story
      @student_team = StudentTeam.find(session[:user_id])
      params[:iteration][:iteration] = get_next_iteration
      @student_team.iterations.create(iteration_params)
      return redirect_to(student_team_path(@student_team))
    end
    
    def assign
      @student_team = StudentTeam.find(params[:id])
      project_title = params[:assign][:project]
      if project_title == "Unassigned" and @student_team.project != nil
        @student_team.project.assigned = false
        @student_team.project.save!
        @student_team.project = nil
      else
        @student_team.project = Project.find_by_title(project_title) || @student_team.project
        if @student_team.project != nil
          @student_team.project.assigned = true
          @student_team.project.save!
        end
      end
      instructor_name = params[:assign][:instructor]
      if instructor_name
        @student_team.instructor = Instructor.find_by_name(instructor_name) || @student_team.instructor
      end
      @student_team.save!
      return redirect_to(student_team_path(@student_team))
    end
    
    def add_gsi_comments
      student_team = StudentTeam.find(params[:id])
      iteration = student_team.iterations.find(params[:iter_id])
      if params[:grades_and_comments][:grades]
        iteration.instructor_grades = params[:grades_and_comments][:grades]
      end
      if params[:grades_and_comments][:private_comments]
        iteration.instructor_private_comments = params[:grades_and_comments][:private_comments]
      end
      if params[:grades_and_comments][:comments]
        iteration.instructor_comments = params[:grades_and_comments][:comments]
      end
      iteration.save!
      return redirect_to(student_team_path(student_team))
    end
    
    def reset_password
      return display_unauthorized_message if not can_edit_profile_page?(params[:id].to_i)
      identify_student_team
    end
    
    def perform_reset_password
      return display_unauthorized_message if not can_edit_profile_page?(params[:id].to_i)
      student_team = StudentTeam.find(params[:id])
      if params[:student_team][:old_password] != student_team.password
        flash[:notice] = "Error: You entered the incorrect old password."
      elsif params[:student_team][:new_password] != params[:student_team][:confirm_new_password]
        flash[:notice] = "Error: The new passwords that you entered did not match."
      else
        student_team.password = params[:student_team][:new_password]
        student_team.save!
        flash[:notice] = "Your password has been succesfully updated."
      end
      return redirect_to(student_team_path(student_team))
    end
    
    private
    
    #--------------------------------------------------------------------------
    # * Identify Student Team
    #--------------------------------------------------------------------------
    
    def identify_student_team
      @student_team = StudentTeam.find(params[:id])
      @can_edit_profile = can_edit_profile_page?(params[:id].to_i)
      @iterations = @student_team.iterations
      @gsi = @student_team.instructor || Instructor.new(name: "Unassigned", email: "Unassigned")
      @project = @student_team.project || Project.new(title: "Unassigned", content: "Unassigned")
      @is_instructor = logged_in_as_instructor
    end
    
    #--------------------------------------------------------------------------
    # * Student Team Creation
    #--------------------------------------------------------------------------
    
    def student_team_params
      params.require(:student_team).permit(:name, :email, :password) 
    end
    
    #--------------------------------------------------------------------------
    # * Iteration Creation
    #--------------------------------------------------------------------------
    
    def iteration_params
      params.require(:iteration).permit(:iteration, :user_stories, :comments)
    end
    
    def get_next_iteration
      next_iteration = 1
      @student_team.iterations.each { |iteration|
        next_iteration = iteration.iteration + 1 if iteration.iteration >= next_iteration
      }
      return next_iteration
    end
    
    #--------------------------------------------------------------------------
    # * Permissions
    #--------------------------------------------------------------------------

    def access_profile_page?(id)
      return true if logged_in_as_instructor 
      return can_edit_profile_page?(id)
    end
    
    def can_edit_profile_page?(id)
      return (logged_in_as_student and session[:user_id] == id)
    end
    
end

app/helpers/student_teams_helper.rb
module StudentTeamsHelper
end

app/views/student_teams/_student_information.haml
#profile-left

  %h3 Student Team Information
  
  %ul
    %li= "Name: #{@student_team.name}".html_safe
    %li= "GSI: #{@gsi.name}".html_safe
    %li= "GSI Email: #{@gsi.email}".html_safe
    - if @can_edit_profile
      %br
      %li= link_to("Edit Profile Page", edit_student_team_path(@student_team))
      %li= link_to("Reset Password", "/student_teams/#{@student_team.id}/reset_password")
  
  %h3 Project Information
  
  %ul
    - if @project.id
      %li= link_to("Project: #{@project.title}", project_path(@project))
    - else
      %li= "Project: #{@project.title}"
  
  %ul
    %li=link_to("GitHub Repository", @student_team.github_link)
    %li=link_to("Heroku Deployment", @student_team.heroku_link)
    %li=link_to("CodeClimate Analysis", @student_team.codeclimate_link)
    %li=link_to("Pivotal Tracker", @student_team.pivotal_link)

app/views/student_teams/edit.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "student_teams/student_information"
  
  #profile-right

    %h2 Edit Student Team
    
    = form_tag(student_team_path(@student_team), method: :put) do
    
      %h3 Student Team Information
      
      = label :student_team, :name, 'Student Team Name:'
      %br
      = text_field :student_team, 'name'
      %p
    
      %h3 Project Information
      
      = label :student_team, :github_link, 'GitHub Link:'
      %br
      = text_field :student_team, 'github_link'
      %p
      = label :student_team, :heroku_link, 'Heroku Link:'
      %br
      = text_field :student_team, 'heroku_link'
      %p
      = label :student_team, :codeclimate_link, 'CodeClimate Link:'
      %br
      = text_field :student_team, 'codeclimate_link'
      %p
      = label :student_team, :pivotal_link, 'PivotalTracker Link:'
      %br
      = text_field :student_team, 'pivotal_link'
      %p
      = submit_tag 'Update Project Information', data: { disable_with: "Please wait..." }

app/views/student_teams/index.html.haml
#container
  =render partial: "main/profile_login"
  
  #student_teams.bigtable
    %h1 List of Student Teams

    %table
      %thead
        %tr
          %th Student Team Name
          %th Student Team Project
      %tbody
        - @student_teams.each_with_index do |team, i|
          %tr
            %td
              =link_to(team.name, student_team_path(team))
            %td= @projects[i].title

app/views/student_teams/new_story.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "student_teams/student_information"
  
  #profile-right
  
    %h2 Submit Story
      
    = form_tag "/student_teams/#{@student_team.id}/submit_story/" do
      = label :iteration, :user_stories, 'User Stories:'
      %br
      = text_area :iteration, 'user_stories'
      %p
      = label :iteration, :email, 'Comments:'
      %br
      = text_area :iteration, 'comments'
      %p
      = submit_tag 'Submit User Story', data: { disable_with: "Please wait..." }

app/views/student_teams/reset_password.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "student_teams/student_information"
  
  #profile-right

    %h2 Reset Password
    
    = form_tag("/student_teams/#{@student_team.id}/reset_password", method: :post) do
      
      = label :student_team, :old_password, 'Old Password:'
      %br
      = password_field :student_team, 'old_password'
      %p
      = label :student_team, :new_password, 'New Password:'
      %br
      = password_field :student_team, 'new_password'
      %p
      = label :student_team, :confirm_new_password, 'Confirm New Password:'
      %br
      = password_field :student_team, 'confirm_new_password'
      %p
      = submit_tag 'Rest Password', data: { disable_with: "Please wait..." }

app/views/student_teams/show.html.haml
#container.profile

  =render partial: "main/profile_login"
  
  =render partial: "student_teams/student_information"
    
  #profile-right
    
    %h2 Iterations
    - if @project.id
      - @iterations.each do |iteration|
        .iteration
          %h3=iteration.iteration_string
          %p
          %strong Date: 
          ="#{iteration.created_at_string}"
          %p
          %strong User Stories:
          %br
          =iteration.user_stories
          %p
          %strong Student Comments:
          %br
          =iteration.comments
          %p
          - if iteration.instructor_grades
            %strong= "Grade: #{iteration.instructor_grades}/100"
          %p
          - if iteration.instructor_comments
            %strong Instructor Comments:
            %br
            =iteration.instructor_comments
            %p
          - if @is_instructor
            - if iteration.instructor_private_comments
              %strong Private Comments:
              %br
              =iteration.instructor_private_comments
              %p
            = form_tag "/student_teams/#{@student_team.id}/add_gsi_comments/#{iteration.id}/" do
              = label :grades_and_comments, :grades, 'Grade to Assign:'
              %br
              = number_field :grades_and_comments, 'grades', id: 'grades'
              %p
              = label :grades_and_comments, :comments, 'Public Comments:'
              %br
              = text_area :grades_and_comments, 'comments', id: 'comments'
              %p
              = label :grades_and_comments, :private_comments, 'Private Comments:'
              %br
              = text_area :grades_and_comments, 'private_comments', id: 'comments'
              %p
              = submit_tag 'Submit', id: 'submit grades and comments', data: { disable_with: "Please wait..." }
      - if @can_edit_profile
        = link_to("Submit Iteration", "/student_teams/#{@student_team.id}/submit_story")
    - else
      - if @is_instructor
        = form_tag "/student_teams/#{@student_team.id}/assign" do
          = label :assign, :project, 'Project to assign:'
          %br
          = text_field :assign, 'project', id: 'assign to project'
          %p
          = label :assign, :instructor, 'Instructor to assign:'
          %br
          = text_field :assign, 'instructor', id: 'assign to instructor'
          %p
          = submit_tag 'Assign', id: 'Assign', data: { disable_with: "Please wait..." }
      - else
        %h3 You have not yet been assigned a project.